global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'algo-bot-spot'
    static_configs:
      - targets: ['algo-bot-spot:8000']
  - job_name: 'algo-bot-forecast'
    static_configs:
      - targets: ['algo-bot-forecast:8001']
